### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#108]
- [x] Implement basic search functionality (single page)
- [ ] Expand new search to profile pages
- [ ] Expand new search to static pages
- [ ] Expand new search to data portal

**Comment by tiagojsag** [comment]
split this up into smaller tasks

**Comment by agnessa** [comment]
What is needed from the search API response? I'm thinking:
`/api/v3/nodes/search?query=car`

```
[
  {id: 587, name: 'Cargill', node_type: 'EXPORTER'},
  ...
]
```

is this enough @tsubik ? the less the better for this endpoint.

**Comment by tsubik** [comment]
Yes, I think that will be it.
