### ISSUE TITLE
Improve labels based on user confusion over terms like ‘summary view’ and ‘node’

### ISSUE THREAD

**Issue by tiagojsag** [Vizzuality/trase#154]
- [ ] "Summary" remains as is
- [ ] "Complete" becomes "All flows"
- [ ] Clicking on "Others" should trigger the search, instead of switching to complete view
- [ ] Icon when hovering over "Others" should be a magnifying glass (see comment below)
- [ ] Rename the "Node selection" recolor by option to "Selection"

**Comment by juancarlosalonso** [comment]
We proposed a new behaviour on a meeting.

We'll need to remove the selector to only enter the "Complete" view by clicking on the OTHER node.
<img width="192" alt="screen shot 2017-12-12 at 17 01 34" src="https://user-images.githubusercontent.com/20836216/33894381-232671dc-df5e-11e7-8f43-fade3924613a.png">

After users click there, a new button will appear on the top of that column to get back to the "Summary" view.
<img width="328" alt="screen shot 2017-12-12 at 17 03 01" src="https://user-images.githubusercontent.com/20836216/33894456-567a793e-df5e-11e7-8b59-8e556c704fa6.png">

**Comment by juancarlosalonso** [comment]
We can change to the following words and test:
Summary --> Top 10
Complete --> All

A related task is to change the action preformed when clicking on an "OTHER" node. Let's change the cursor to a search icon and open the search box instead of entering the Complete view.
<img width="464" alt="screen shot 2017-12-12 at 17 20 56" src="https://user-images.githubusercontent.com/20836216/33895453-d5c71cea-df60-11e7-819a-f4ad6f42e785.png">

**Comment by tiagojsag** [comment]
Updated issue description based on  https://basecamp.com/1756858/projects/12498794/todos/322939066
